preset: laravel

enabled:
  - strict
  - unalign_double_arrow

disabled:
  - concat_without_spaces
  - phpdoc_no_package
  - simplified_null_return

finder:
  exclude:
    - "tests"
  name:
    - "*.php"
